### ISSUE TITLE
Using index instead of key with JsonObject

### ISSUE THREAD

**Issue by Ivolutio** [AngelQuirogaM/NiceJson#4]
Hi, first of all, thanks for this library. I've been writing my scripts with it now and one thing I've noticed that would be very useful, is to be able to do JsonObject[0], JsonObject[1], etc, instead of JsonObject["key1"], JsonObject["key2"].
I am just missing how to do this.. or is there a workaround for this? 
This is my JSON and I want to do:

```
{
	"name": "Forest Biome",

	"multipliers":{ 
		"steps": 1.00,
    	"xp_gain": 0.20,
    	"damage": 0.50
	},

	"tiles":{
		"Forest Tile":{
			"Hname": "forest_basic",
			"rarity": 100,
			"minHeight": 1,
			"maxHeight": 1000
		}
                "Plains Tile":{
			"Hname": "grass_basic",
			"rarity": 50,
			"minHeight": 1,
			"maxHeight": 1000
		}
	}
}
```

and I was trying to do: 
```
List<TileType> tiles = new List<TileType>();
//insert a loop to get every object listed in tiles {} later
tiles.Add(Tiles[json["tiles"][0]["Hname"]])
tiles.Add(Tiles[json["tiles"][1]["Hname"]]);
```
This worked fine; `tiles.Add(Tiles[json["tiles"]["Forest Tile"]["Hname"]]);`

Thanks, 
Pixel

**Comment by AngelQuirogaM** [comment]
Hi Pixel,

first of all, thank you for using my library. Secondly I will ask yourself to reconsider the way you are storing your data. If you see the way you are using your data. It could be something like this:

	"tiles"[
		{
			"Hname": "forest_basic",
                        "Htitle": "Forest Tile",
			"rarity": 100,
			"minHeight": 1,
			"maxHeight": 1000
		}
         ]
I told you so because array's and dictionaries are thought to be used in a very different way. Also Json's standars doesn't say anything about a dictionary order. In that way thinking in the source of your json you could be in a trouble if the order changes.

Anyway if you want to stay that way you can use something like this:

`         
`Tiles.Add(Tiles[json["tiles"][json["tiles"].Keys.ElementAt(0)]["Hname"];`
`


But I advise against to do this type of coding.
If you have any idea of why this should be a nice idea tell me and I would think about it.

Thank you for your time :)
